name: Deploy Staging 🚀

on:
  push:
    branches:
      - main

jobs:
  deploy-to-staging:
    name: Deploy to Staging Server
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Run Deployment Script via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SSH_HOST_STAGING }}
          username: ${{ secrets.SSH_USER_NAME_STAGING }}
          key: ${{ secrets.SSH_PRIVATE_KEY_STAGING }}
          script: |
            - name: Clear DNS cache
              run: |
                sudo systemctl restart systemd-resolved
                
            # Step 1: Check and prepare the application directory
            echo "Checking application directory..."
            if [ -d "${{ vars.APP_STG_PATH }}" ]; then
              echo "Directory exists. Proceeding with update..."
              cd "${{ vars.APP_STG_PATH }}"
              ssh-keygen -R 54.255.86.78
              ssh-keyscan -H ${{ secrets.SSH_HOST_STAGING }} >> ~/.ssh/known_hosts
              cat ~/.ssh/known_hosts | grep 54.255.86.78
              cat ~/.ssh/known_hosts | grep 54.169.176.157
              sudo docker compose down pacmusic-stg
              git pull origin main
            else
              echo "Directory does not exist. Cloning repository..."
              ssh-keyscan github.com >> ~/.ssh/known_hosts
              git clone ${{ secrets.GIT_URL }} "${{ vars.APP_STG_PATH }}"
              cd "${{ vars.APP_STG_PATH }}"
            fi

            # Step 2: Create .env file
            echo "Creating .env file..."
            echo "APP_STG_PORT=${{ secrets.APP_STG_PORT }}" > .env
            echo "MINIO_STG_ENDPOINT=${{ secrets.MINIO_STG_ENDPOINT }}" >> .env
            echo "MINIO_STG_ACCESS_KEY=${{ secrets.MINIO_STG_ACCESS_KEY }}" >> .env
            echo "MINIO_STG_SECRET_KEY=${{ secrets.MINIO_STG_SECRET_KEY }}" >> .env

            # Step 3: Start the application
            echo "Starting application..."
            sudo docker compose up --build --detach pacmusic-stg

      - name: Test Hit Endpoint
        run: |
          sleep 10
          curl ${{ secrets.STG_URL }}
