name: Push to Container Registry 🛒

on:
  push:
    tags:
      - "*"

jobs:
  push-to-container-registry:
    name: Push Image to Container Registry
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Debug Context - List Files
      - name: List files in context
        run: |
          echo "Listing files in the app directory:"
          ls -l ./app
          echo "Tree structure of the app directory:"
          tree ./app

      # Step 3: Login to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 4: Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 5: Build and Push Images
      - name: Build and Push Images
        uses: docker/build-push-action@v4
        with:
          context: ./app  # Menetapkan context ke folder 'app'
          dockerfile: ./app/Dockerfile  # Menetapkan path lengkap ke Dockerfile di dalam folder 'app'
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pacmusic:${{ github.ref_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/pacmusic:latest
